# Test NasmX86 2021-05-16 at 00:46:51

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Install Data::Table::Text
      run: |
        sudo cpan install -T Data::Table::Text

    - name: Install GitHub::Crud
      run: |
        sudo cpan install -T Digest::SHA1

    - name: Install Asm::C
      run: |
        sudo cpan install -T Asm::C

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Install tree
      run: |
        sudo apt-get install -y tree

    - name: Download Intel Sde
      run: |
        curl https://software.intel.com/content/dam/develop/external/us/en/documents/downloads/sde-external-8.63.0-2021-01-18-lin.tar.bz2 > sde.tar.bz2
        tree

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Test
      run: |
        perl lib/Nasm/X86.pm

    - name: Prove t/1.t
      if: always()
      run: |
        prove -Ilib t/1.t

    - name: Prove t/10.t
      if: always()
      run: |
        prove -Ilib t/10.t

    - name: Prove t/11.t
      if: always()
      run: |
        prove -Ilib t/11.t

    - name: Prove t/12.t
      if: always()
      run: |
        prove -Ilib t/12.t

    - name: Prove t/13.t
      if: always()
      run: |
        prove -Ilib t/13.t

    - name: Prove t/14.t
      if: always()
      run: |
        prove -Ilib t/14.t

    - name: Prove t/2.t
      if: always()
      run: |
        prove -Ilib t/2.t

    - name: Prove t/3.t
      if: always()
      run: |
        prove -Ilib t/3.t

    - name: Prove t/4.t
      if: always()
      run: |
        prove -Ilib t/4.t

    - name: Prove t/5.t
      if: always()
      run: |
        prove -Ilib t/5.t

    - name: Prove t/6.t
      if: always()
      run: |
        prove -Ilib t/6.t

    - name: Prove t/6a.t
      if: always()
      run: |
        prove -Ilib t/6a.t

    - name: Prove t/7.t
      if: always()
      run: |
        prove -Ilib t/7.t

    - name: Prove t/8.t
      if: always()
      run: |
        prove -Ilib t/8.t

    - name: Prove t/9.t
      if: always()
      run: |
        prove -Ilib t/9.t


    - name: Prove
      run: |
        #prove -Ilib
