# Test NasmX86 2021-05-15 at 01:25:06

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Data::Table::Text
      run: |
        sudo cpan install -T Data::Table::Text

    - name: Install GitHub::Crud
      run: |
        sudo cpan install -T Digest::SHA1

    - name: Install Asm::C
      run: |
        sudo cpan install -T Asm::C

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Install tree
      run: |
        sudo apt-get install -y tree

    - name: Download Intel Sde
      run: |
        curl https://software.intel.com/content/dam/develop/external/us/en/documents/downloads/sde-external-8.63.0-2021-01-18-lin.tar.bz2 > sde.tar.bz2
        tree

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Test
      run: |
        perl lib/Nasm/X86.pm

    - name: Prove
      run: |
        prove -Ilib

    - name: Prove /home/phil/perl/cpan/NasmX86/t/1.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/1.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/10.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/10.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/11.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/11.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/12.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/12.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/13.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/13.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/2.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/2.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/3.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/3.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/4.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/4.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/5.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/5.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/6.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/6.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/7.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/7.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/8.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/8.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/9.t
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/9.t

    - name: Prove /home/phil/perl/cpan/NasmX86/t/z.txt
      run: |
        prove -Ilib /home/phil/perl/cpan/NasmX86/t/z.txt

